name: Checkout
on: [push]
jobs:
  checkout-and-display-files:
  runs-on: macOS-latest
  steps:
    - name: List files before
      run: ls-a
    - name: Checkout
      run: |
        git init
        git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
        git fetch origin
        git checkout main
    - name: List Files After
      run: ls-a