name: Repository Events
on:
    push:
    pull_request: 
        types: [opened, assigned, synchronize, reopened]
    issues:
        types: [opened]

jobs:
    checkout-test: #Github_REF is the main branch here since we push to main branch
        runs-on: macOS-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3