name: First WorkFlow
on: [push]

jobs:
    run-shell-commands:
        runs-on: macOS-13 #use macOS-13 here for the real thing
        steps:
            - name: echo a string
              run: echo "hello world"
            - name: multiline commands
              run: |
                node -v
                npm -v