name: Manually Triggered
on:
    workflow_dispatch:
        inputs:
            string:
                description: A description string input
                type: string
                required: true
                default: "Default value"
            number:
                description: A number input
                default: 6
                type: number
            option:
                description: "An options input"
                required: true
                default: "Option 3"
                type: choice
                options:
                    - Option 1
                    - Option 2
                    - Option 3
            boolean:
                description: A boolean input
                required: false
                type: boolean
            environment:
                description: "An environment input"
                type: environment
                required: true

jobs:
    log-info:
        runs-on: MacOS-latest
        steps:
            - run: echo $GITHUB_REF
            - run: |
                echo "String: ${{ inputs.string }}"
                echo "Number: ${{ inputs.number }}"
                echo "Option: ${{ inputs.option }}"
                echo "Boolean: ${{ inputs.boolean }} "
                echo "Environment: ${{ inputs.environment }}"