name: Workflow Commands
on: [push]

jobs:
     testing-wf-commands:
        runs-on: macOS-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting error with params
              run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Error message"
            - name: Debug message
              run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Debug message"
            - name: Warning
              run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Warning message"
            - name: Notice title
              run: echo "::notice title=Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Notice message"
            - name: Group of logs
              run: |
                echo "::group::Group title"
                echo "Inside group"
                echo "::endgroup::"
            - name: Masking a value
              run: echo "::add-mask::Hardcoded secret string"
            - name: Echo secret string
              run: echo "Hardcoded secret string"