name: Workflow Run
on: 
    workflow_run:
        workflows: [Repository Events]
        types: [completed]
        branches:
            - main  # This implies that we only want workflow_run here to trigger once the Repository Events workflow is completed on the main branch
jobs:
    echo-string:
        runs-on: macOS-latest
        steps:
            - run: echo "I was triggered because `Repository Events` was completed"